---
- name: Create a password for user
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
    - name: Create a password for user debian
      user:
        name: debian
        password: '$6$E.zQ95uegyQ/pklQ$/GhYs8800HAdpkKL8F80EKZLBhXPRY0gk6CjnkqDokaSAH05p4NkNVO2udw9vWhagdjqk.ye3lH7vGwsU1R9a1'
